### ISSUE TITLE
maybe you can help me

### ISSUE THREAD

**Issue by plexigras** [elliottsj/combine-loader#85]
i want to combine multiple loaders into a single loader

so i can do `require('custom-loader!test.css')` instead of having to inline the whole config when i want different loader behavior then the one i configured in the webpack config.

**Comment by elliottsj** [comment]
If your goal is to have `custom-loader` be an alias for a longer loader configuration, try out the `resolveLoader.alias` option. e.g. https://stackoverflow.com/questions/31313088/webpack-loader-aliases

**Comment by plexigras** [comment]
thank you, this is exactly what i was looking for.
